SPEED = 100
HEALTH_BAR = {
  x = 100,
  y = 5,
  thickness = 1,
  padding = 10,
}
AMMO_BAR = {
  x = 117,
  y = 5,
  r = 3,
  thickness = 1,
  padding = 10
}
STATUS_LINE_OFFSET = 17
GAME_OVER_OFFSET = 16
NEW_HIGH_SCORE_OFFSET = 32
GAME_OVER_MULT = 2
SPRITES = {
  player = 1,
  astroid1 = 2,
  astroid2 = 3,
  astroid3 = 4,
}
ASTROID_INTERVAL = .5
HITSTOP_INTERVAL = .2
DAMAGE = 5
BULLET_SPEED = 200
RELOAD_SPEED = 1
MAX_AMMO = 5
ASTROID_SCORE = 100
TIMER_OFFSET = 120
SCORE_OFFSET = 75
HIGH_SCORE_OFFSET = 15
SHOCKWAVE_FRAMES = 12
TITLE_POSITION = {
  x = usagi.GAME_W / 2 - 68,
  y = 50
}
PLAY_POSITION = {
  x = TITLE_POSITION.x + 80,
  y = TITLE_POSITION.y + 45,
}
QUIT_POSITION = {
  x = TITLE_POSITION.x + 80,
  y = TITLE_POSITION.y + 60
}
CURSOR_POSITIONS = {
  PLAY_POSITION.y - 2,
  QUIT_POSITION.y - 2
}
